### ISSUE TITLE
Tasks do not show up content

### ISSUE THREAD

**Issue by vmario89** [tripleFA/khanos#1]
Hi @tripleFA,
happy that you are maintaining Khanos. I am one of the users of your Khanos releases and recently i figured out that Khanos stopped showing issue content. I can edit, move, close any ticket, but i cannot see the details at the first view (see below). I have no idea what happened. I installed your version 1.2.0 and did not change anything at the kanboard server instance for months now. Maybe you have an idea?

when running debug with adb

```
dnf install android-tools #install adb
adb logcat --pid=`adb shell pidof -s com.gojaponte.khanos`
```

The log trace:
```
07-21 13:48:18.252 16352 16422 D ProfileInstaller: Skipping profile installation for com.gojaponte.khanos
07-21 13:49:48.023 16352 16375 I flutter : Bad state: No element
07-21 13:49:48.025 16352 16375 I flutter : #0      ListBase.firstWhere (dart:collection/list.dart:132)
07-21 13:49:48.025 16352 16375 I flutter : #1      _TaskPageState._taskInfo.<anonymous closure> (package:khanos/src/pages/task_page.dart:202)
07-21 13:49:48.025 16352 16375 I flutter : #2      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:612)
07-21 13:49:48.025 16352 16375 I flutter : #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198)
07-21 13:49:48.025 16352 16375 I flutter : #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086)
07-21 13:49:48.025 16352 16375 I flutter : #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
07-21 13:49:48.025 16352 16375 I flutter : #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
07-21 13:49:48.025 16352 16375 I flutter : #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780)
07-21 13:49:48.025 16352 16375 I flutter : #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903)
07-21 13:49:48.025 16352 16375 I flutter : #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358)
07-21 13:49:48.025 16352 16375 I flutter : #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284)
07-21 13:49:48.025 16352 16375 I flutter : #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214)
07-21 13:49:48.025 16352 16375 I flutter : #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072)
07-21 13:49:48.025 16352 16375 I flutter : #13     _invoke (dart:ui/hooks.dart:142)
07-21 13:49:48.025 16352 16375 I flutter : #14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359)
07-21 13:49:48.025 16352 16375 I flutter : #15     _drawFrame (dart:ui/hooks.dart:112)
07-21 13:50:05.355 16352 16375 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
07-21 13:50:05.883 16352 16375 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
07-21 13:50:05.908 16352 16375 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
07-21 13:50:05.927 16352 16391 I OpenGLRenderer: Davey! duration=19511ms; Flags=1, FrameTimelineVsyncId=4222940, IntendedVsync=137146582651694, Vsync=137146582651694, InputEventId=784229849, HandleInputStart=137146582994480, AnimationStart=137146582995365, PerformTraversalsStart=137146582996250, DrawStart=137146603900575, FrameDeadline=137146615985026, FrameInterval=137146582992657, FrameStartTime=16666666, SyncQueued=137146604066096, SyncStart=137146604231930, IssueDrawCommandsStart=137146604396930, SwapBuffers=137146606281096, FrameCompleted=137166093838559, DequeueBufferDuration=920313, QueueBufferDuration=1349688, GpuCompleted=137166093838559, SwapBuffersCompleted=137146608328440, DisplayPresentTime=0, 
07-21 13:50:06.167 16352 16375 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

this is how it looks like:

![image](https://github.com/tripleFA/khanos/assets/5631071/d72617cc-1f10-4b06-814a-b66194c85f4f)

best regards, Mario

**Comment by tripleFA** [comment]
Hi,
I can reproduce this issue but only on 1 of my many tasks.
 Is this problem present in all tasks or only in a few of them?

I'll try to give a look this week.

**Comment by vmario89** [comment]
hi. no it happens not on all tasks, but on a larger number. we have around 300 tasks in our instance and it feels like 50% do not work. i did not find out any reasonable cause yet (like task name, swimlane, column, ...)

**Comment by tripleFA** [comment]
Hi,
It should be fixed in the latest release.
Can you check it?

Issue was a 'null' created_date not handled from JSON

**Comment by vmario89** [comment]
Hey. Thanks for your work on it! I had a look on it, but it still appears. the following errors i got from the adb logcat:

```
07-25 15:51:49.109  8043  8043 W ojaponte.khanos: type=1400 audit(0.0:41066): avc: denied { read } for name="max_map_count" dev="proc" ino=2257973 scontext=u:r:untrusted_app:s0:c139,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=com.gojaponte.khanos
07-25 15:51:49.118  8043  8043 I AdrenoGLES-0: QUALCOMM build                   : 559e78c, Ib9d997268a
07-25 15:51:49.118  8043  8043 I AdrenoGLES-0: Build Date                       : 10/13/20
07-25 15:51:49.118  8043  8043 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.02
07-25 15:51:49.118  8043  8043 I AdrenoGLES-0: Local Branch                     : mybrancheb0d76cb-f27a-f1ff-9cdc-1458d0b52ae8
07-25 15:51:49.118  8043  8043 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
07-25 15:51:49.118  8043  8043 I AdrenoGLES-0: Remote Branch                    : NONE
07-25 15:51:49.118  8043  8043 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
07-25 15:51:49.118  8043  8043 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
07-25 15:51:49.118  8043  8043 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
07-25 15:51:49.118  8043  8043 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
07-25 15:51:49.124  8043  8043 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
07-25 15:51:49.156  8043  8043 W FlutterActivityAndFragmentDelegate: A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
07-25 15:51:49.191  8043  8067 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
07-25 15:51:49.199  8043  8061 I Gralloc4: Adding additional valid usage bits: 0x8202000
07-25 15:51:54.244  8043  8066 I flutter : Bad state: No element
07-25 15:51:54.245  8043  8066 I flutter : #0      ListBase.firstWhere (dart:collection/list.dart:132)
07-25 15:51:54.245  8043  8066 I flutter : #1      _TaskPageState._taskInfo.<anonymous closure> (package:khanos/src/pages/task_page.dart:202)
07-25 15:51:54.245  8043  8066 I flutter : #2      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:612)
07-25 15:51:54.245  8043  8066 I flutter : #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198)
07-25 15:51:54.245  8043  8066 I flutter : #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086)
07-25 15:51:54.245  8043  8066 I flutter : #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
07-25 15:51:54.245  8043  8066 I flutter : #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
07-25 15:51:54.245  8043  8066 I flutter : #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780)
07-25 15:51:54.245  8043  8066 I flutter : #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903)
07-25 15:51:54.245  8043  8066 I flutter : #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358)
07-25 15:51:54.245  8043  8066 I flutter : #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284)
07-25 15:51:54.245  8043  8066 I flutter : #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214)
07-25 15:51:54.245  8043  8066 I flutter : #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072)
07-25 15:51:54.245  8043  8066 I flutter : #13     _invoke (dart:ui/hooks.dart:142)
07-25 15:51:54.246  8043  8066 I flutter : #14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359)
07-25 15:51:54.246  8043  8066 I flutter : #15     _drawFrame (dart:ui/hooks.dart:112)
07-25 15:51:54.528  8043  8164 D ProfileInstaller: Installing profile for com.gojaponte.khanos
07-25 15:51:58.858  8043  8066 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
07-25 15:53:47.507  8043  8058 I ojaponte.khano: oneway function results for code 1599295570 on binder at 0xb400007d00647fd0 will be dropped but finished with status UNKNOWN_TRANSACTION
07-25 15:53:58.383  8043  8058 I ojaponte.khano: oneway function results for code 1599295570 on binder at 0xb400007d00647fd0 will be dropped but finished with status UNKNOWN_TRANSACTION
07-25 15:54:05.806  8043  8058 I ojaponte.khano: oneway function results for code 1599295570 on binder at 0xb400007d00647fd0 will be dropped but finished with status UNKNOWN_TRANSACTION
07-25 15:54:53.824  8043  8058 I ojaponte.khano: oneway function results for code 1599295570 on binder at 0xb400007d00647fd0 will be dropped but finished with status UNKNOWN_TRANSACTION
07-25 15:55:39.259  8043  8058 I OpenGLRenderer: Davey! duration=198052ms; Flags=1, FrameTimelineVsyncId=8148326, IntendedVsync=306579033116538, Vsync=306579033116538, InputEventId=848392800, HandleInputStart=306579033612335, AnimationStart=306579033613220, PerformTraversalsStart=306579033613793, DrawStart=306579048734576, FrameDeadline=306579066449870, FrameInterval=306579033610199, FrameStartTime=16666666, SyncQueued=306579048813117, SyncStart=306579048858638, IssueDrawCommandsStart=306579049721191, SwapBuffers=306579051778847, FrameCompleted=306777085718158, DequeueBufferDuration=1475053, QueueBufferDuration=846980, GpuCompleted=306777085718158, SwapBuffersCompleted=306579052882649, DisplayPresentTime=0, 
07-25 15:55:44.004  8043  8066 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
07-25 15:55:50.065  8043  8066 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

the issue seems to be `ListBase.firstWhere (dart:collection/list.dart:132)` but i dont see where this is located in source code. seems to be some compiled output code, which i do not have.

**Comment by tripleFA** [comment]
Le logcat output is not relevant. 
I don't have the issue anymore. I tried with a test task with all possible options.
Could you check the API return for a task that work and a task that don't?

```
curl -u "user:password" -d '{"jsonrpc": "2.0", "method": "getTask", "id": 0, "params": {"task_id": 316}}' https://kanboard.domain.tld/jsonrpc.php
```
with "task_id" the number of your task.

**Comment by vmario89** [comment]
Hi thanks for your help. You pointed me to a good direction using the API. i found the problem: i changed the auth system from local user db to LDAP a while ago. New users were created, old ones deleted

works:
```
{
  "jsonrpc": "2.0",
  "result": {
    "id": 426,
    "title": "Neue Origami Flyer",
    "description": "Origami-Flyer fast alle. brauchen neue. Wegen Adressaufdruck lohnt sich das wahrscheinlich nicht mehr dieses Jahr",
    "date_creation": 1686036326,
    "color_id": "yellow",
    "project_id": 9,
    "column_id": 35,
    "owner_id": 10,
    "position": 2,
    "is_active": true,
    "date_completed": null,
    "score": 0,
    "date_due": 0,
    "category_id": 0,
    "creator_id": 10,
    "date_modification": 1686036326,
    "reference": "",
    "date_started": 0,
    "time_spent": "0",
    "time_estimated": "0",
    "swimlane_id": 10,
    "date_moved": 1686036326,
    "recurrence_status": 0,
    "recurrence_trigger": 0,
    "recurrence_factor": 0,
    "recurrence_timeframe": 0,
    "recurrence_basedate": 0,
    "recurrence_parent": null,
    "recurrence_child": null,
    "priority": 0,
    "external_provider": null,
    "external_uri": null,
    "owner_gp": 0,
    "owner_ms": 37,
    "url": "https://board.REDACTED.tld/task/426",
    "color": {
      "name": "Yellow"
    }
  },
  "id": 0
}

```



fails:
```
{
  "jsonrpc": "2.0",
  "result": {
    "id": 169,
    "title": "50mm Button-Rohlinge",
    "description": "",
    "date_creation": 1657305116,
    "color_id": "yellow",
    "project_id": 9,
    "column_id": 35,
    "owner_id": 0,
    "position": 7,
    "is_active": true,
    "date_completed": null,
    "score": 0,
    "date_due": 0,
    "category_id": 0,
    "creator_id": 4,
    "date_modification": 1657305116,
    "reference": "",
    "date_started": 0,
    "time_spent": "0",
    "time_estimated": "0",
    "swimlane_id": 10,
    "date_moved": 1657305116,
    "recurrence_status": 0,
    "recurrence_trigger": 0,
    "recurrence_factor": 0,
    "recurrence_timeframe": 0,
    "recurrence_basedate": 0,
    "recurrence_parent": null,
    "recurrence_child": null,
    "priority": 0,
    "external_provider": null,
    "external_uri": null,
    "owner_gp": 0,
    "owner_ms": 0,
    "url": "https://board.REDACTED.tld/task/169",
    "color": {
      "name": "Yellow"
    }
  },
  "id": 0
}
```

found out that `creator_id` is the issue. I updated the creator_id on the failing task manually in database (`UPDATE tasks SET creator_id=10 WHERE id=169;`) but this is not a clean way. Would have to do that for a lot of tasks manually.

Is it possible to include some check if user exists or was deleted in the data model of Khanos?

**Comment by tripleFA** [comment]
Hi, 
Can you check if this solves your issue : 
https://www.swisstransfer.com/d/b67a4d53-0eeb-430e-b0b8-ecd5b5190b7f

If that works i'll make a release.

**Comment by vmario89** [comment]
hi! Thank you for fixing this. Indeed, works perfectly - it shows N/A on users/grups, which is fine:
![grafik](https://github.com/tripleFA/khanos/assets/5631071/9f126d7b-b66f-4742-b2d5-fc9c0fe52dc5)

**Comment by vmario89** [comment]
i am closing that issue for now, but if you like you can reference it to your commits
